### ISSUE TITLE
tklbam-backup - Jitter variable.

### ISSUE THREAD

**Issue by ronankeane** [turnkeylinux/tklbam#3]
This seems to be causing issues with hourly backups. I.e. 2 backups occurring nearly at the same time.

**Comment by JedMeister** [comment]
Hey @ronankeane - Firstly sorry to hear of your troubles and apologies on the lack of response. I only just came across this...

We track all of our bugs/issues in a consolidated [TurnKey tracker](https://github.com/turnkeylinux/tracker/issues/) so posts to individual repos often get missed. We need to make that clearer and more explicit. 

Regardless if you could give us some more info about your problem (and a suggested fix if you have one) over on the general tracker, that'd be awesome. I haven't actually been involved with TKLBAM development much but I regularly touch base with Liraz (the lead TKLBAM dev).

Alternatively [our support forums](https://www.turnkeylinux.org/forum/support) are the place for support. I try to respond there regularly but feel free to bump any posts that remain unanswered after a bit of a wait. And/or ping me via email (jeremy AT turnkeylinux.org).

Closing this now, but as I say please feel free to open an issue on the main tracker and/or a nerw thread on the support forums.
